as yet unclassified
CurrenciesAtoF
	|tmp|
	tmp := OrderedCollection  new.
tmp add: (self new country: 'Abkhazia'; currencyName: 'Georgian lari'; symbol: 'ლ'; currency: 'GEL').
tmp add: (self new country: 'Afghanistan'; currencyName: 'Afghan afghani'; symbol: '؋'; currency: 'AFN').
tmp add: (self new country: 'Akrotiri and Dhekelia'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'Albania'; currencyName: 'Albanian lek'; symbol: 'L'; currency: 'ALL').
tmp add: (self new country: 'Alderney'; currencyName: 'British pound'; symbol: '£'; currency: 'GBP').
tmp add: (self new country: 'Algeria'; currencyName: 'Algerian dinar'; symbol: 'د.ج'; currency: 'DZD').
tmp add: (self new country: 'Andorra'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'Angola'; currencyName: 'Angolan kwanza'; symbol: 'Kz'; currency: 'AOA').
tmp add: (self new country: 'Anguilla'; currencyName: 'East Caribbean dollar'; symbol: '$'; currency: 'XCD').
tmp add: (self new country: 'Antigua and Barbuda'; currencyName: 'East Caribbean dollar'; symbol: '$'; currency: 'XCD').
tmp add: (self new country: 'Argentina'; currencyName: 'Argentine peso'; symbol: '$'; currency: 'ARS').
tmp add: (self new country: 'Armenia'; currencyName: 'Armenian dram'; symbol: 'դր.'; currency: 'AMD').
tmp add: (self new country: 'Aruba'; currencyName: 'Aruban florin'; symbol: 'ƒ'; currency: 'AWG').
tmp add: (self new country: 'Ascension Island'; currencyName: 'Saint Helena pound'; symbol: '£'; currency: 'SHP').
tmp add: (self new country: 'Australia'; currencyName: 'Australian dollar'; symbol: '$'; currency: 'AUD').
tmp add: (self new country: 'Austria'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'Azerbaijan'; currencyName: 'Azerbaijani manat'; symbol: ' '; currency: 'AZN').
tmp add: (self new country: 'Bahamas, The'; currencyName: 'Bahamian dollar'; symbol: '$'; currency: 'BSD').
tmp add: (self new country: 'Bahrain'; currencyName: 'Bahraini dinar'; symbol: 'ب.د'; currency: 'BHD').
tmp add: (self new country: 'Bangladesh'; currencyName: 'Bangladeshi taka'; symbol: '৳'; currency: 'BDT').
tmp add: (self new country: 'Barbados'; currencyName: 'Barbadian dollar'; symbol: '$'; currency: 'BBD').
tmp add: (self new country: 'Belarus'; currencyName: 'Belarusian ruble'; symbol: 'Br'; currency: 'BYR').
tmp add: (self new country: 'Belgium'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'Belize'; currencyName: 'Belize dollar'; symbol: '$'; currency: 'BZD').
tmp add: (self new country: 'Benin'; currencyName: 'West African CFA franc'; symbol: 'Fr'; currency: 'XOF').
tmp add: (self new country: 'Bermuda'; currencyName: 'Bermudian dollar'; symbol: '$'; currency: 'BMD').
tmp add: (self new country: 'Bhutan'; currencyName: 'Bhutanese ngultrum'; symbol: ''; currency: 'BTN').
tmp add: (self new country: 'Bolivia'; currencyName: 'Bolivian boliviano'; symbol: 'Bs.'; currency: 'BOB').
tmp add: (self new country: 'Bosnia and Herzegovina'; currencyName: 'Bosnia and Herzegovina convertible mark'; symbol: 'KM or КМ'; currency: 'BAM').
tmp add: (self new country: 'Botswana'; currencyName: 'Botswana pula'; symbol: 'P'; currency: 'BWP').
tmp add: (self new country: 'Brazil'; currencyName: 'Brazilian real'; symbol: 'R$'; currency: 'BRL').
tmp add: (self new country: 'British Indian Ocean Territory'; currencyName: 'United States dollar'; symbol: '$'; currency: 'USD').
tmp add: (self new country: 'British Virgin Islands'; currencyName: 'United States dollar'; symbol: '$'; currency: 'USD').
tmp add: (self new country: 'Brunei'; currencyName: 'Brunei dollar'; symbol: '$'; currency: 'BND').
tmp add: (self new country: 'Bulgaria'; currencyName: 'Bulgarian lev'; symbol: 'лв'; currency: 'BGN').
tmp add: (self new country: 'Burkina Faso'; currencyName: 'West African CFA franc'; symbol: 'Fr'; currency: 'XOF').
tmp add: (self new country: 'Burundi'; currencyName: 'Burundian franc'; symbol: 'Fr'; currency: 'BIF').
tmp add: (self new country: 'Cambodia'; currencyName: 'Cambodian riel'; symbol: '៛'; currency: 'KHR').
tmp add: (self new country: 'Cameroon'; currencyName: 'Central African CFA franc'; symbol: 'Fr'; currency: 'XAF').
tmp add: (self new country: 'Canada'; currencyName: 'Canadian dollar'; symbol: '$'; currency: 'CAD').
tmp add: (self new country: 'Cape Verde'; currencyName: 'Cape Verdean escudo'; symbol: '$ or Esc'; currency: 'CVE').
tmp add: (self new country: 'Cayman Islands'; currencyName: 'Cayman Islands dollar'; symbol: '$'; currency: 'KYD').
tmp add: (self new country: 'Central African Republic'; currencyName: 'Central African CFA franc'; symbol: 'Fr'; currency: 'XAF').
tmp add: (self new country: 'Chad'; currencyName: 'Central African CFA franc'; symbol: 'Fr'; currency: 'XAF').
tmp add: (self new country: 'Chile'; currencyName: 'Chilean peso'; symbol: '$'; currency: 'CLP').
tmp add: (self new country: 'China, People’s Republic of'; currencyName: 'Chinese yuan'; symbol: '元'; currency: 'CNY').
tmp add: (self new country: 'Cocos (Keeling) Islands'; currencyName: 'Australian dollar'; symbol: '$'; currency: 'AUD').
tmp add: (self new country: 'Colombia'; currencyName: 'Colombian peso'; symbol: '$'; currency: 'COP').
tmp add: (self new country: 'Comoros'; currencyName: 'Comorian franc'; symbol: 'Fr'; currency: 'KMF').
tmp add: (self new country: 'Congo, Democratic Republic of the'; currencyName: 'Congolese franc'; symbol: 'Fr'; currency: 'CDF').
tmp add: (self new country: 'Congo, Republic of the'; currencyName: 'Central African CFA franc'; symbol: 'Fr'; currency: 'XAF').
tmp add: (self new country: 'Cook Islands'; currencyName: 'New Zealand dollar'; symbol: '$'; currency: 'NZD').
tmp add: (self new country: 'Costa Rica'; currencyName: 'Costa Rican colón'; symbol: '₡'; currency: 'CRC').
tmp add: (self new country: 'Côte d’Ivoire'; currencyName: 'West African CFA franc'; symbol: 'Fr'; currency: 'XOF').
tmp add: (self new country: 'Croatia'; currencyName: 'Croatian kuna'; symbol: 'kn'; currency: 'HRK').
tmp add: (self new country: 'Cuba'; currencyName: 'Cuban convertible peso'; symbol: '$'; currency: 'CUC').
tmp add: (self new country: 'Cuba'; currencyName: 'Cuban peso'; symbol: '$'; currency: 'CUP').
tmp add: (self new country: 'Cyprus'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'Czech Republic'; currencyName: 'Czech koruna'; symbol: 'Kč'; currency: 'CZK').
tmp add: (self new country: 'Denmark'; currencyName: 'Danish krone'; symbol: 'kr'; currency: 'DKK').
tmp add: (self new country: 'Djibouti'; currencyName: 'Djiboutian franc'; symbol: 'Fr'; currency: 'DJF').
tmp add: (self new country: 'Dominica'; currencyName: 'East Caribbean dollar'; symbol: '$'; currency: 'XCD').
tmp add: (self new country: 'Dominican Republic'; currencyName: 'Dominican peso'; symbol: '$'; currency: 'DOP').
tmp add: (self new country: 'East Timor'; currencyName: 'United States dollar'; symbol: '$'; currency: 'USD').
tmp add: (self new country: 'Ecuador'; currencyName: 'United States dollar'; symbol: '$'; currency: 'USD').
tmp add: (self new country: 'Egypt'; currencyName: 'Egyptian pound'; symbol: '£ or ج.م'; currency: 'EGP').
tmp add: (self new country: 'El Salvador'; currencyName: 'Salvadoran colón'; symbol: '₡'; currency: 'SVC').
tmp add: (self new country: 'Equatorial Guinea'; currencyName: 'Central African CFA franc'; symbol: 'Fr'; currency: 'XAF').
tmp add: (self new country: 'Eritrea'; currencyName: 'Eritrean nakfa'; symbol: 'Nfk'; currency: 'ERN').
tmp add: (self new country: 'Estonia'; currencyName: 'Estonian kroon'; symbol: 'KR'; currency: 'EEK').
tmp add: (self new country: 'Ethiopia'; currencyName: 'Ethiopian birr'; symbol: ''; currency: 'ETB').
tmp add: (self new country: 'Falkland Islands'; currencyName: 'Falkland Islands pound'; symbol: '£'; currency: 'FKP').
tmp add: (self new country: 'Faroe Islands'; currencyName: 'Danish krone'; symbol: 'kr'; currency: 'DKK').
tmp add: (self new country: 'Fiji'; currencyName: 'Fijian dollar'; symbol: '$'; currency: 'FJD').
tmp add: (self new country: 'Finland'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'France'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'French Polynesia'; currencyName: 'CFP franc'; symbol: 'Fr'; currency: 'XPF').

^tmp. 	