as yet unclassified
CurrenciesNtoS
	|tmp|
	tmp := OrderedCollection  new.
	tmp add: (self new country: 'Nagorno-Karabakh'; currencyName: 'Armenian dram'; symbol: 'դր.'; currency: 'AMD').
tmp add: (self new country: 'Namibia'; currencyName: 'Namibian dollar'; symbol: '$'; currency: 'NAD').
tmp add: (self new country: 'Nauru'; currencyName: 'Australian dollar'; symbol: '$'; currency: 'AUD').
tmp add: (self new country: 'Nepal'; currencyName: 'Nepalese rupee'; symbol: '₨'; currency: 'NPR').
tmp add: (self new country: 'Netherlands'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'Netherlands Antilles'; currencyName: 'Netherlands Antillean guilder'; symbol: 'ƒ'; currency: 'ANG').
tmp add: (self new country: 'New Caledonia'; currencyName: 'CFP franc'; symbol: 'Fr'; currency: 'XPF').
tmp add: (self new country: 'New Zealand'; currencyName: 'New Zealand dollar'; symbol: '$'; currency: 'NZD').
tmp add: (self new country: 'Nicaragua'; currencyName: 'Nicaraguan córdoba'; symbol: 'C$'; currency: 'NIO').
tmp add: (self new country: 'Niger'; currencyName: 'West African CFA franc'; symbol: 'Fr'; currency: 'XOF').
tmp add: (self new country: 'Nigeria'; currencyName: 'Nigerian naira'; symbol: '₦'; currency: 'NGN').
tmp add: (self new country: 'Niue'; currencyName: 'New Zealand dollar'; symbol: '$'; currency: 'NZD').
tmp add: (self new country: 'Northern Cyprus'; currencyName: 'Turkish lira'; symbol: '₤'; currency: 'TRY').
tmp add: (self new country: 'Northern Mariana Islands'; currencyName: 'United States dollar'; symbol: '$'; currency: 'USD').
tmp add: (self new country: 'Norway'; currencyName: 'Norwegian krone'; symbol: 'kr'; currency: 'NOK').
tmp add: (self new country: 'Oman'; currencyName: 'Omani rial'; symbol: 'ر.ع.'; currency: 'OMR').
tmp add: (self new country: 'Pakistan'; currencyName: 'Pakistani rupee'; symbol: '₨'; currency: 'PKR').
tmp add: (self new country: 'Palau'; currencyName: 'Palauan dollar'; symbol: '$'; currency: 'None').
tmp add: (self new country: 'Palestine'; currencyName: 'Israeli new sheqel'; symbol: '₪'; currency: 'ILS').
tmp add: (self new country: 'Panama'; currencyName: 'Panamanian balboa'; symbol: 'B/.'; currency: 'PAB').
tmp add: (self new country: 'Papua New Guinea'; currencyName: 'Papua New Guinean kina'; symbol: 'K'; currency: 'PGK').
tmp add: (self new country: 'Paraguay'; currencyName: 'Paraguayan guaraní'; symbol: '₲'; currency: 'PYG').
tmp add: (self new country: 'Peru'; currencyName: 'Peruvian nuevo sol'; symbol: 'S/.'; currency: 'PEN').
tmp add: (self new country: 'Philippines'; currencyName: 'Philippine peso'; symbol: '₱'; currency: 'PHP').
tmp add: (self new country: 'Pitcairn Islands'; currencyName: 'New Zealand dollar'; symbol: '$'; currency: 'NZD').
tmp add: (self new country: 'Poland'; currencyName: 'Polish złoty'; symbol: 'zł'; currency: 'PLN').
tmp add: (self new country: 'Portugal'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'Qatar'; currencyName: 'Qatari riyal'; symbol: 'ر.ق'; currency: 'QAR').
tmp add: (self new country: 'Romania'; currencyName: 'Romanian leu'; symbol: 'L'; currency: 'RON').
tmp add: (self new country: 'Russia'; currencyName: 'Russian ruble'; symbol: 'руб.'; currency: 'RUB').
tmp add: (self new country: 'Rwanda'; currencyName: 'Rwandan franc'; symbol: 'Fr'; currency: 'RWF').
tmp add: (self new country: 'Saint Helena'; currencyName: 'Saint Helena pound'; symbol: '£'; currency: 'SHP').
tmp add: (self new country: 'Saint Kitts and Nevis'; currencyName: 'East Caribbean dollar'; symbol: '$'; currency: 'XCD').
tmp add: (self new country: 'Saint Lucia'; currencyName: 'East Caribbean dollar'; symbol: '$'; currency: 'XCD').
tmp add: (self new country: 'Saint Vincent and the Grenadines'; currencyName: 'East Caribbean dollar'; symbol: '$'; currency: 'XCD').
tmp add: (self new country: 'Samoa'; currencyName: 'Samoan tala'; symbol: 'T'; currency: 'WST').
tmp add: (self new country: 'San Marino'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'São Tomé and Príncipe'; currencyName: 'São Tomé and Príncipe dobra'; symbol: 'Db'; currency: 'STD').
tmp add: (self new country: 'Saudi Arabia'; currencyName: 'Saudi riyal'; symbol: 'ر.س'; currency: 'SAR').
tmp add: (self new country: 'Senegal'; currencyName: 'West African CFA franc'; symbol: 'Fr'; currency: 'XOF').
tmp add: (self new country: 'Serbia'; currencyName: 'Serbian dinar'; symbol: 'дин. or din.'; currency: 'RSD').
tmp add: (self new country: 'Seychelles'; currencyName: 'Seychellois rupee'; symbol: '₨'; currency: 'SCR').
tmp add: (self new country: 'Sierra Leone'; currencyName: 'Sierra Leonean leone'; symbol: 'Le'; currency: 'SLL').
tmp add: (self new country: 'Singapore'; currencyName: 'Singapore dollar'; symbol: '$'; currency: 'SGD').
tmp add: (self new country: 'Slovakia'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'Slovenia'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'Solomon Islands'; currencyName: 'Solomon Islands dollar'; symbol: '$'; currency: 'SBD').
tmp add: (self new country: 'Somalia'; currencyName: 'Somali shilling'; symbol: 'Sh'; currency: 'SOS').
tmp add: (self new country: 'Somaliland'; currencyName: 'Somaliland shilling'; symbol: 'Sh'; currency: 'None').
tmp add: (self new country: 'South Africa'; currencyName: 'South African rand'; symbol: 'R'; currency: 'ZAR').
tmp add: (self new country: 'South Georgia and the South Sandwich Islands'; currencyName: 'British pound'; symbol: '£'; currency: 'GBP').
tmp add: (self new country: 'South Ossetia'; currencyName: 'Georgian lari'; symbol: 'ლ'; currency: 'GEL').
tmp add: (self new country: 'Spain'; currencyName: 'Euro'; symbol: '€'; currency: 'EUR').
tmp add: (self new country: 'Sri Lanka'; currencyName: 'Sri Lankan rupee'; symbol: 'Rs'; currency: 'LKR').
tmp add: (self new country: 'Sudan'; currencyName: 'Sudanese pound'; symbol: '£'; currency: 'SDG').
tmp add: (self new country: 'Suriname'; currencyName: 'Surinamese dollar'; symbol: '$'; currency: 'SRD').
tmp add: (self new country: 'Swaziland'; currencyName: 'Swazi lilangeni'; symbol: 'L'; currency: 'SZL').
tmp add: (self new country: 'Sweden'; currencyName: 'Swedish krona'; symbol: 'kr'; currency: 'SEK').
tmp add: (self new country: 'Switzerland'; currencyName: 'Swiss franc'; symbol: 'Fr'; currency: 'CHF').
tmp add: (self new country: 'Syria'; currencyName: 'Syrian pound'; symbol: '£ or ل.س'; currency: 'SYP').

^tmp.