currencies
currenciesGtoM
	| tmp |
	tmp := OrderedCollection new.
	tmp
		add:
			(self new
				country: 'Gabon';
				currencyName: 'Central African CFA franc';
				symbol: 'Fr';
				currency: 'XAF').
	tmp
		add:
			(self new
				country: 'Gambia, The';
				currencyName: 'Gambian dalasi';
				symbol: 'D';
				currency: 'GMD').
	tmp
		add:
			(self new
				country: 'Georgia';
				currencyName: 'Georgian lari';
				symbol: 'ლ';
				currency: 'GEL').
	tmp
		add:
			(self new
				country: 'Germany';
				currencyName: 'Euro';
				symbol: '€';
				currency: 'EUR').
	tmp
		add:
			(self new
				country: 'Ghana';
				currencyName: 'Ghanaian cedi';
				symbol: '₵';
				currency: 'GHS').
	tmp
		add:
			(self new
				country: 'Gibraltar';
				currencyName: 'Gibraltar pound';
				symbol: '£';
				currency: 'GIP').
	tmp
		add:
			(self new
				country: 'Greece';
				currencyName: 'Euro';
				symbol: '€';
				currency: 'EUR').
	tmp
		add:
			(self new
				country: 'Grenada';
				currencyName: 'East Caribbean dollar';
				symbol: '$';
				currency: 'XCD').
	tmp
		add:
			(self new
				country: 'Guatemala';
				currencyName: 'Guatemalan quetzal';
				symbol: 'Q';
				currency: 'GTQ').
	tmp
		add:
			(self new
				country: 'Guernsey';
				currencyName: 'British pound';
				symbol: '£';
				currency: 'GBP').
	tmp
		add:
			(self new
				country: 'Guinea';
				currencyName: 'Guinean franc';
				symbol: 'Fr';
				currency: 'GNF').
	tmp
		add:
			(self new
				country: 'Guinea-Bissau';
				currencyName: 'West African CFA franc';
				symbol: 'Fr';
				currency: 'XOF').
	tmp
		add:
			(self new
				country: 'Guyana';
				currencyName: 'Guyanese dollar';
				symbol: '$';
				currency: 'GYD').
	tmp
		add:
			(self new
				country: 'Haiti';
				currencyName: 'Haitian gourde';
				symbol: 'G';
				currency: 'HTG').
	tmp
		add:
			(self new
				country: 'Honduras';
				currencyName: 'Honduran lempira';
				symbol: 'L';
				currency: 'HNL').
	tmp
		add:
			(self new
				country: 'Hong Kong';
				currencyName: 'Hong Kong dollar';
				symbol: '$';
				currency: 'HKD').
	tmp
		add:
			(self new
				country: 'Hungary';
				currencyName: 'Hungarian forint';
				symbol: 'Ft';
				currency: 'HUF').
	tmp
		add:
			(self new
				country: 'Iceland';
				currencyName: 'Icelandic króna';
				symbol: 'kr';
				currency: 'ISK').
	tmp
		add:
			(self new
				country: 'Indonesia';
				currencyName: 'Indonesian rupiah';
				symbol: 'Rp';
				currency: 'IDR').
	tmp
		add:
			(self new
				country: 'Iran';
				currencyName: 'Iranian rial';
				symbol: '﷼';
				currency: 'IRR').
	tmp
		add:
			(self new
				country: 'Iraq';
				currencyName: 'Iraqi dinar';
				symbol: 'ع.د';
				currency: 'IQD').
	tmp
		add:
			(self new
				country: 'Ireland';
				currencyName: 'Euro';
				symbol: '€';
				currency: 'EUR').
	tmp
		add:
			(self new
				country: 'Isle of Man';
				currencyName: 'British pound';
				symbol: '£';
				currency: 'GBP').
	tmp
		add:
			(self new
				country: 'Israel';
				currencyName: 'Israeli new sheqel';
				symbol: '₪';
				currency: 'ILS').
	tmp
		add:
			(self new
				country: 'Italy';
				currencyName: 'Euro';
				symbol: '€';
				currency: 'EUR').
	tmp
		add:
			(self new
				country: 'Jamaica';
				currencyName: 'Jamaican dollar';
				symbol: '$';
				currency: 'JMD').
	tmp
		add:
			(self new
				country: 'Jersey';
				currencyName: 'British pound';
				symbol: '£';
				currency: 'GBP').
	tmp
		add:
			(self new
				country: 'Jordan';
				currencyName: 'Jordanian dinar';
				symbol: 'د.ا';
				currency: 'JOD').
	tmp
		add:
			(self new
				country: 'Kazakhstan';
				currencyName: 'Kazakhstani tenge';
				symbol: '〒';
				currency: 'KZT').
	tmp
		add:
			(self new
				country: 'Kenya';
				currencyName: 'Kenyan shilling';
				symbol: 'Sh';
				currency: 'KES').
	tmp
		add:
			(self new
				country: 'Kiribati';
				currencyName: 'Australian dollar';
				symbol: '$';
				currency: 'AUD').
	tmp
		add:
			(self new
				country: 'Korea, North';
				currencyName: 'North Korean won';
				symbol: '₩';
				currency: 'KPW').
	tmp
		add:
			(self new
				country: 'Korea, South';
				currencyName: 'South Korean won';
				symbol: '₩';
				currency: 'KRW').
	tmp
		add:
			(self new
				country: 'Kosovo';
				currencyName: 'Euro';
				symbol: '€';
				currency: 'EUR').
	tmp
		add:
			(self new
				country: 'Kuwait';
				currencyName: 'Kuwaiti dinar';
				symbol: 'د.ك';
				currency: 'KWD').
	tmp
		add:
			(self new
				country: 'Kyrgyzstan';
				currencyName: 'Kyrgyzstani som';
				symbol: '';
				currency: 'KGS').
	tmp
		add:
			(self new
				country: 'Laos';
				currencyName: 'Lao kip';
				symbol: '₭';
				currency: 'LAK').
	tmp
		add:
			(self new
				country: 'Latvia';
				currencyName: 'Latvian lats';
				symbol: 'Ls';
				currency: 'LVL').
	tmp
		add:
			(self new
				country: 'Lebanon';
				currencyName: 'Lebanese pound';
				symbol: 'ل.ل';
				currency: 'LBP').
	tmp
		add:
			(self new
				country: 'Lesotho';
				currencyName: 'Lesotho loti';
				symbol: 'L';
				currency: 'LSL').
	tmp
		add:
			(self new
				country: 'Liberia';
				currencyName: 'Liberian dollar';
				symbol: '$';
				currency: 'LRD').
	tmp
		add:
			(self new
				country: 'Libya';
				currencyName: 'Libyan dinar';
				symbol: 'ل.د';
				currency: 'LYD').
	tmp
		add:
			(self new
				country: 'Liechtenstein';
				currencyName: 'Swiss franc';
				symbol: 'Fr';
				currency: 'CHF').
	tmp
		add:
			(self new
				country: 'Lithuania';
				currencyName: 'Lithuanian litas';
				symbol: 'Lt';
				currency: 'LTL').
	tmp
		add:
			(self new
				country: 'Luxembourg';
				currencyName: 'Euro';
				symbol: '€';
				currency: 'EUR').
	tmp
		add:
			(self new
				country: 'Macau';
				currencyName: 'Macanese pataca';
				symbol: 'P';
				currency: 'MOP').
	tmp
		add:
			(self new
				country: 'Macedonia, Republic of';
				currencyName: 'Macedonian denar';
				symbol: 'ден';
				currency: 'MKD').
	tmp
		add:
			(self new
				country: 'Madagascar';
				currencyName: 'Malagasy ariary';
				symbol: '';
				currency: 'MGA').
	tmp
		add:
			(self new
				country: 'Malawi';
				currencyName: 'Malawian kwacha';
				symbol: 'MK';
				currency: 'MWK').
	tmp
		add:
			(self new
				country: 'Malaysia';
				currencyName: 'Malaysian ringgit';
				symbol: 'RM';
				currency: 'MYR').
	tmp
		add:
			(self new
				country: 'Maldives';
				currencyName: 'Maldivian rufiyaa';
				symbol: 'ރ.';
				currency: 'MVR').
	tmp
		add:
			(self new
				country: 'Mali';
				currencyName: 'West African CFA franc';
				symbol: 'Fr';
				currency: 'XOF').
	tmp
		add:
			(self new
				country: 'Malta';
				currencyName: 'Euro';
				symbol: '€';
				currency: 'EUR').
	tmp
		add:
			(self new
				country: 'Marshall Islands';
				currencyName: 'United States dollar';
				symbol: '$';
				currency: 'USD').
	tmp
		add:
			(self new
				country: 'Mauritania';
				currencyName: 'Mauritanian ouguiya';
				symbol: 'UM';
				currency: 'MRO').
	tmp
		add:
			(self new
				country: 'Mauritius';
				currencyName: 'Mauritian rupee';
				symbol: '₨';
				currency: 'MUR').
	tmp
		add:
			(self new
				country: 'Mexico';
				currencyName: 'Mexican peso';
				symbol: '$';
				currency: 'MXN').
	tmp
		add:
			(self new
				country: 'Micronesia';
				currencyName: 'United States dollar';
				symbol: '$';
				currency: 'USD').
	tmp
		add:
			(self new
				country: 'Moldova';
				currencyName: 'Moldovan leu';
				symbol: 'L';
				currency: 'MDL').
	tmp
		add:
			(self new
				country: 'Monaco';
				currencyName: 'Euro';
				symbol: '€';
				currency: 'EUR').
	tmp
		add:
			(self new
				country: 'Mongolia';
				currencyName: 'Mongolian tögrög';
				symbol: '₮';
				currency: 'MNT').
	tmp
		add:
			(self new
				country: 'Montenegro';
				currencyName: 'Euro';
				symbol: '€';
				currency: 'EUR').
	tmp
		add:
			(self new
				country: 'Montserrat';
				currencyName: 'East Caribbean dollar';
				symbol: '$';
				currency: 'XCD').
	tmp
		add:
			(self new
				country: 'Morocco';
				currencyName: 'Moroccan dirham';
				symbol: 'د.م.';
				currency: 'MAD').
	tmp
		add:
			(self new
				country: 'Mozambique';
				currencyName: 'Mozambican metical';
				symbol: 'MTn';
				currency: 'MZN').
	tmp
		add:
			(self new
				country: 'Myanmar';
				currencyName: 'Myanma kyat';
				symbol: 'K';
				currency: 'MMK').
	^ tmp