updating
currencyCodesAndSymbolsNToZ
	^ {('NAD' -> '$').
	('NGN' -> '₦').
	('NIO' -> 'C$').
	('NOK' -> 'kr').
	('NPR' -> '₨').
	('NZD' -> '$').
	('None' -> 'Sh').
	('OMR' -> 'ر.ع.').
	('PAB' -> 'B/.').
	('PEN' -> 'S/.').
	('PGK' -> 'K').
	('PHP' -> '₱').
	('PKR' -> '₨').
	('PLN' -> 'zł').
	('PYG' -> '₲').
	('QAR' -> 'ر.ق').
	('RON' -> 'L').
	('RSD' -> 'дин. or din.').
	('RUB' -> 'руб.').
	('RWF' -> 'Fr').
	('SAR' -> 'ر.س').
	('SBD' -> '$').
	('SCR' -> '₨').
	('SDG' -> '£').
	('SEK' -> 'kr').
	('SGD' -> '$').
	('SHP' -> '£').
	('SLL' -> 'Le').
	('SOS' -> 'Sh').
	('SRD' -> '$').
	('STD' -> 'Db').
	('SVC' -> '₡').
	('SYP' -> '£ or ل.س').
	('SZL' -> 'L').
	('THB' -> '฿').
	('TJS' -> 'ЅМ').
	('TMM' -> 'm').
	('TND' -> 'د.ت').
	('TOP' -> 'T$').
	('TRY' -> 'TL').
	('TTD' -> '$').
	('TWD' -> '$').
	('TZS' -> 'Sh').
	('UAH' -> '₴').
	('UGX' -> 'Sh').
	('USD' -> '$').
	('UYU' -> '$').
	('UZS' -> '').
	('VEF' -> 'Bs F').
	('VND' -> '₫').
	('VUV' -> 'Vt').
	('WST' -> 'T').
	('XAF' -> 'Fr').
	('XCD' -> '$').
	('XOF' -> 'Fr').
	('XPF' -> 'Fr').
	('YER' -> '﷼').
	('ZAR' -> 'R').
	('ZMK' -> 'ZK').
	('ZWR' -> '$')}