currencies
currenciesTtoZ
	| tmp |
	tmp := OrderedCollection new.
	tmp
		add:
			(self new
				country: 'Taiwan (Republic of China)';
				currencyName: 'New Taiwan dollar';
				symbol: '$';
				currency: 'TWD').
	tmp
		add:
			(self new
				country: 'Tajikistan';
				currencyName: 'Tajikistani somoni';
				symbol: 'ЅМ';
				currency: 'TJS').
	tmp
		add:
			(self new
				country: 'Tanzania';
				currencyName: 'Tanzanian shilling';
				symbol: 'Sh';
				currency: 'TZS').
	tmp
		add:
			(self new
				country: 'Thailand';
				currencyName: 'Thai baht';
				symbol: '฿';
				currency: 'THB').
	tmp
		add:
			(self new
				country: 'Togo';
				currencyName: 'West African CFA franc';
				symbol: 'Fr';
				currency: 'XOF').
	tmp
		add:
			(self new
				country: 'Tonga';
				currencyName: 'Tongan paʻanga';
				symbol: 'T$';
				currency: 'TOP').
	tmp
		add:
			(self new
				country: 'Trinidad and Tobago';
				currencyName: 'Trinidad and Tobago dollar';
				symbol: '$';
				currency: 'TTD').
	tmp
		add:
			(self new
				country: 'Tristan da Cunha';
				currencyName: 'Saint Helena pound';
				symbol: '£';
				currency: 'SHP').
	tmp
		add:
			(self new
				country: 'Tunisia';
				currencyName: 'Tunisian dinar';
				symbol: 'د.ت';
				currency: 'TND').
	tmp
		add:
			(self new
				country: 'Turkey';
				currencyName: 'Turkish lira';
				symbol: 'TL';
				currency: 'TRY').
	tmp
		add:
			(self new
				country: 'Turkmenistan';
				currencyName: 'Turkmenistani manat';
				symbol: 'm';
				currency: 'TMM').
	tmp
		add:
			(self new
				country: 'Turks and Caicos Islands';
				currencyName: 'United States dollar';
				symbol: '$';
				currency: 'USD').
	tmp
		add:
			(self new
				country: 'Tuvalu';
				currencyName: 'Australian dollar';
				symbol: '$';
				currency: 'AUD').
	tmp
		add:
			(self new
				country: 'Uganda';
				currencyName: 'Ugandan shilling';
				symbol: 'Sh';
				currency: 'UGX').
	tmp
		add:
			(self new
				country: 'Ukraine';
				currencyName: 'Ukrainian hryvnia';
				symbol: '₴';
				currency: 'UAH').
	tmp
		add:
			(self new
				country: 'United Arab Emirates';
				currencyName: 'United Arab Emirates dirham';
				symbol: 'د.إ';
				currency: 'AED').
	tmp
		add:
			(self new
				country: 'Uruguay';
				currencyName: 'Uruguayan peso';
				symbol: '$';
				currency: 'UYU').
	tmp
		add:
			(self new
				country: 'Uzbekistan';
				currencyName: 'Uzbekistani som';
				symbol: '';
				currency: 'UZS').
	tmp
		add:
			(self new
				country: 'Vanuatu';
				currencyName: 'Vanuatu vatu';
				symbol: 'Vt';
				currency: 'VUV').
	tmp
		add:
			(self new
				country: 'Vatican City';
				currencyName: 'Euro';
				symbol: '€';
				currency: 'EUR').
	tmp
		add:
			(self new
				country: 'Venezuela';
				currencyName: 'Venezuelan bolívar';
				symbol: 'Bs F';
				currency: 'VEF').
	tmp
		add:
			(self new
				country: 'Vietnam';
				currencyName: 'Vietnamese đong';
				symbol: '₫';
				currency: 'VND').
	tmp
		add:
			(self new
				country: 'Wallis and Futuna';
				currencyName: 'CFP franc';
				symbol: 'Fr';
				currency: 'XPF').
	tmp
		add:
			(self new
				country: 'Western Sahara';
				currencyName: 'Moroccan dirham';
				symbol: 'د.م.';
				currency: 'MAD').
	tmp
		add:
			(self new
				country: 'Yemen';
				currencyName: 'Yemeni rial';
				symbol: '﷼';
				currency: 'YER').
	tmp
		add:
			(self new
				country: 'Zambia';
				currencyName: 'Zambian kwacha';
				symbol: 'ZK';
				currency: 'ZMK').
	tmp
		add:
			(self new
				country: 'Zimbabwe';
				currencyName: 'Zimbabwean dollar';
				symbol: '$';
				currency: 'ZWR').
	^ tmp